### ISSUE TITLE
Examples 1-3 typo

### ISSUE THREAD

**Issue by azev77** [RJDennis/SolveDSGE.jl#21]
```julia
julia> filename = "model3b.txt"
"model3b.txt"

julia> path3 = joinpath(@__DIR__,filename)
"/Users/AZevelev/Dropbox/COMPUTATION/Julia/DE_OC/SolveDSGE_ProjectionPerturbation/AZ_1/model3b.txt"

julia> process_model(path3)
The model's variables are now in this order: ["tech", "cap", "conslag", "cons"]

julia> processed_filename = "processed_model5a.txt"
"processed_model5a.txt"

julia> processed_path3 =  joinpath(@__DIR__,processed_filename)
"/Users/AZevelev/Dropbox/COMPUTATION/Julia/DE_OC/SolveDSGE_ProjectionPerturbation/AZ_1/processed_model5a.txt"

julia> dsge3 = retrieve_processed_model(processed_path3)
ERROR: could not open file /Users/AZevelev/Dropbox/COMPUTATION/Julia/DE_OC/SolveDSGE_ProjectionPerturbation/AZ_1/processed_model5a_processed.txt
Stacktrace:
 [1] include(::Function, ::Module, ::String) at ./Base.jl:380
 [2] include at ./Base.jl:368 [inlined]
 [3] include at /Users/AZevelev/.julia/packages/SolveDSGE/GMwhJ/src/SolveDSGE.jl:1 [inlined]
 [4] retrieve_processed_model(::String) at /Users/AZevelev/.julia/packages/SolveDSGE/GMwhJ/src/parser_functions.jl:692
 [5] top-level scope at none:1
```

**Comment by azev77** [comment]
@RJDennis 
how difficult would it be to write this model in Julia rather than `model.txt` file?

I say this because I often like to solve the same model for a grid of parameters & this is easier to do in Julia than in a `model.txt` file.

**Comment by RJDennis** [comment]
I've just tagged a release that should fix this silly file-name error in the three examples.

Regarding your question, it is not difficult to write the model by hand in Julia.  This is what I used to do (and still do depending on the project), but I understood that people find a parser useful as it allows them to write their models in a more natural way.  The processed model file is useful in that regard in that it shows you what you need to write.

Although I don't have things set up so that a model can be solved automatically for a range of different parameter values, the current way of processing a model and then reading in the processed output is useful in that regard.  It is not too difficult to process a bunch of models (that may just differ by the value of one parameter) up front and then retrieve all of the models into a single workspace and solve them in a single session.
