### ISSUE TITLE
Running solve_model inside a function

### ISSUE THREAD

**Issue by albep** [RJDennis/SolveDSGE.jl#25]
I'm getting an "applicable method may be too new: running in world age X, while current world is Y" error when using the `solve_model function` inside another function (which I need in order for instance to solve repeatedly the model for different parameter values).

It seems to be an issue caused by running the `retrieve_processed_model` function in global scope or inside a function.

A simple example to replicate the issue is as follows (taken from your `model3b` example model):

```julia
using SolveDSGE

filename = "model3b.txt"
path3 = joinpath(@__DIR__,filename)
process_model(path3)

processed_filename = "model3b_processed.txt"
processed_path3 =  joinpath(@__DIR__,processed_filename)

function testmeplz(processed_path3)
    dsge3 = retrieve_processed_model(processed_path3)

    x3 = [0.05, 3.05, 0.7, 0.7]

    tol = 1e-8
    maxiters = 1000

    ss3 = compute_steady_state(dsge3,x3,tol,maxiters)

    N = PerturbationScheme(ss3,1.0,"first")
    soln_fo3 = solve_model(dsge3,N)
    return soln_fo3
end

testmeplz(processed_path3)
```

This simple example generates the same kind of error I get, but for the `compute_steady_state` function. When solving my model, I get it with the `solve_model` function because I have a customized function that solves the steady state exactly, instead of relying on a solver.

If in the previous example I pasted you move `dsge3 = retrieve_processed_model(processed_path3)` outside the `testmeplz` function, things work as you would expect. This makes me think the issue has to do with running `retrieve_processed_model` in global or local scope.

Do you know how I can solve this issue? Is there something you can do on your side?

Many thanks,
Alberto

**Comment by RJDennis** [comment]
Alberto,

this "world age" problem is not something that I was aware of.  But google it in the context of Julia and you'll get some hits.  The problem is that ```retrive_processed_model()``` generates code.  Because functions allow methods to be changed, the compiler doesn't know that methods are not being changed each time that function (testmeplz()) gets called.  I don't have a really good solution to this problem right now.  Basically, I didn't expect that ```retrive_processed_model()``` would ever be called from within a function like you are doing.

For the specific example above, you can overcome the problem as follows:

```
using SolveDSGE

filename = "model3b.txt"
path3 = joinpath(@__DIR__,filename)
process_model(path3)

processed_filename = "model3b_processed.txt"
processed_path3 =  joinpath(@__DIR__,processed_filename)

dsge3 = retrieve_processed_model(processed_path3)

function testmeplz(processed_path3)
    
    global dsge3
    dsge3 = retrieve_processed_model(processed_path3)

    x3 = [0.05, 3.05, 0.7, 0.7]

    tol = 1e-8
    maxiters = 1000

    ss3 = compute_steady_state(dsge3,x3,tol,maxiters)

    N = PerturbationScheme(ss3,1.0,"first")
    soln_fo3 = solve_model(dsge3,N)
    return soln_fo3
end

testmeplz(processed_path3)
```

but whether this works for your actual use case I don't know.

**Comment by albep** [comment]
Thanks @RJDennis, we're on the same page. And the solution you proposed is exactly what I'm doing at the moment, though it's not ideal. I think it's quite important to be able to run all the functions, including `retrieve_processed_model()` inside another function.

Digging into the code, I did notice that there is this call to `include()` which I think is causing the issue:
https://github.com/RJDennis/SolveDSGE.jl/blob/8ad8b1297dc9dfbda746e9621f273b293e7a98fc/src/parser_functions.jl#L692

Unfortunately I've never done metaprogramming in Julia, but I'd guess the call to `include()` could be replaced by appropriate macros that allow you to go directly from the inputs in `create_processed_model_file()` to the outputs needed by the `struct` `REModel()`. Have you thought/tried to do that before?

**Comment by RJDennis** [comment]
Alberto,

when a function is created in real time within another function and then called before reaching the gloabl scope, then this "world age" problem will occur. (For example, in your code, the first time ```testmeplz(processed_path3)``` is called it will error, but not on the second time.  It doesn't matter how that function is being created: eval(), include(), or some other method involving meta programming.  My current approach that uses include() was introduced a couple of versions ago.  Before that I was using eval().  Both approaches would not do what you want.

I don't know why you need to call ```retrieve_processed_model()``` inside a function.  Instead of trying to solve "one model" for 20 (say) different parameterizations, maybe you could approach it as solving 20 different models.  Setting up the models is mostly a cut and paste.  Then reading in, processing, and solving each model could be done with a loop.

**Comment by albep** [comment]
I did notice that the second time I run the code the "world age" error doesn't show up, but at the same time, further runs of the code ended up changing the outputs of previous runs - something which only happened when running `retrieve_processed_model_file()` inside a function.

The reason I need to call `retrieve_processed_model_file()` inside a function is that I'm using simulated-method-of-moments to estimate a number of parameters in order to match some moments/IRFs.

Looking forward to seeing your approach to deal with the issue. I just found that calling `Base.invokelatest()` on each function generated by `include()` could work, but I haven't tried it yet.

**Comment by RJDennis** [comment]
The latest version of the package should allow you to solve your model for a range of parameter values using a for loop, employing the assign_parameters() function to update the model structure with the parameter value after the model has been processed.  I'm hopeful that you can see from the user guide and example four how to implement this.  The code snippet below might also help.
```
filename = "model1a.txt"
model_path = joinpath(@__DIR__,filename)

process_model(model_path)

dsge = retrieve_processed_model(model_path)

s = [1.0:0.1:2.0;] # In this case these are values for sigma, the inverse elasticity of intertemporal substitution.

x = [0.05, 3.05, 0.7]
tol = 1e-8
maxiters = 1000
N   = PerturbationScheme(ss,1.0,"first")

for i in eachindex(s)

    dsgebar = assign_parameters(dsge,[s[i]])

    ss = compute_steady_state(dsgebar,x,tol,maxiters)
   
    soln_fo = solve_model(dsgebar,N)
    println(soln_fo.hx)
   
end
```

**Comment by albep** [comment]
Thanks a lot Richard, looking forward to trying it!
