### ISSUE TITLE
Question about estimation

### ISSUE THREAD

**Issue by mcreel** [RJDennis/SolveDSGE.jl#33]
First, thanks for this very nice package! I saw in the commit comment for v0.4 that changes were made to facilitate estimation, and that it is possible to solve the model passing in the parameters. This is something I would like to do, to provide students an example of estimation using simulated moments and related methods. I don't see documentation for how to do this - is any available, or planned? I can probably figure it out looking at the code, but if you're planning to add more details, I'm happy to wait a bit.

If you are interested, I'm planning to move the code for the model at page 451 of the document https://github.com/mcreel/Econometrics/blob/master/econometrics.pdf to Julia, using SolveDSGE.jl, instead of Dynare, This will help a lot to explain methods that need to do simulations at different parameter values.

**Comment by RJDennis** [comment]
Hi Michael,

thanks for your interest in the package.

The key function you'll need is called assign_parameters().  It is discussed a bit in section 4.1 of the user guide.  Basically, for any parameters that you want to esimate leave the parameter value blank in the model file. So parameters that are not going to be estimated will get a value assigned in the model file and parameters that are to be estimated will not.  For example, instead of sigma = 2.0, you would just list sigma in the model file.  Then when the model gets parsed and processed you will be told the order of the variables in the system and which parameters do not have a value assigned.  Then, after the model has been processed, you can assign a value to these parameters by using the assign_parameters() function; the values go in a vector in the order that the parameters were listed when it was parsed.  I'm not sure how clear the above is, but you can see it in action by looking at the code for model2a in the test folder.

With this functionality, you can repeatedly assign parameter values and then solve the resulting model.

Hope this helps.

Richard

**Comment by mcreel** [comment]
Thanks, that's very clear. I looked over the code and docs too quickly.
